services:
  gymmanagement.api:
    image: ${DOCKER_REGISTRY-}gymmanagementapi
    container_name: Gym-Management-API
    build:
      context: .
      dockerfile: src/GymManagement.Api/Dockerfile
    depends_on:
      - gym-management-db

  gym-management-db:
    image: postgres:latest
    container_name: Gym-Management.Db
    environment:
      - POSTGRES_DB=gym-management-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  gym-management-idp:
    image: quay.io/keycloak/keycloak
    container_name: Gym-Management-Idp
    command: start-dev --import-realm
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/bookify-realm-export.json
    volumes:
      - ./.containers/idp:/opt/keycloak/keycloak/standalone/data
      - ./.files/bookify-realm-export.json:/opt/keycloak/data/import/bookify-realm-export.json
    ports:
      - 18080:8080

  bookify-seq:
    image: datalust/seq:latest
    container_name: Gym-Management.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80